server:
  port: ${port:0}
  #port: 8091
spring:
  data:
    mongodb:
        uri: mongodb://localhost:27017/db-ms-account
  cloud:
    discovery:
        enabled: true
    gateway:
        discovery:
            locator:
                enabled: true
                lower-case-service-id: true
             

eureka:
  instance:
     hostname: localhost
     #hostname: eureka-service-contenedor
     #prefer-ip-address: true
     instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
